-- =========================================================================
-- RatedWorktops — Complete Database Setup & Migration Script
-- =========================================================================
-- Run this ENTIRE script in Supabase Dashboard -> SQL Editor
-- It will:
--   1. Fix the brands & colours tables (add missing columns)
--   2. Create the categories table
--   3. Set up full RLS policies for anon, authenticated & public roles
--   4. Reload the PostgREST schema cache so changes take effect instantly
-- =========================================================================


-- =========================================================================
-- SECTION 1: BRANDS TABLE
-- =========================================================================
-- Your brands table already exists with BIGINT id. This adds any missing
-- columns and ensures everything the admin dashboard writes is accepted.
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Quartz',
    description TEXT DEFAULT '',
    enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add columns that may be missing from an earlier migration
ALTER TABLE public.brands ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Quartz';
ALTER TABLE public.brands ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';
ALTER TABLE public.brands ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT true;
ALTER TABLE public.brands ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();


-- =========================================================================
-- SECTION 2: COLOURS TABLE
-- =========================================================================
-- Your colours table already exists with BIGINT id and brand_id.
-- This adds the missing columns: brand_name, finish, image_url
-- that the admin dashboard needs to save stone colour data.
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.colours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT REFERENCES public.brands(id) ON DELETE CASCADE,
    brand_name TEXT DEFAULT '',
    name TEXT NOT NULL,
    sku TEXT DEFAULT '',
    finish TEXT DEFAULT 'Polished',
    texture TEXT DEFAULT 'marble',
    image_url TEXT DEFAULT '',
    enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add columns that may be missing from an earlier migration
ALTER TABLE public.colours ADD COLUMN IF NOT EXISTS brand_id BIGINT;
ALTER TABLE public.colours ADD COLUMN IF NOT EXISTS brand_name TEXT DEFAULT '';
ALTER TABLE public.colours ADD COLUMN IF NOT EXISTS sku TEXT DEFAULT '';
ALTER TABLE public.colours ADD COLUMN IF NOT EXISTS finish TEXT DEFAULT 'Polished';
ALTER TABLE public.colours ADD COLUMN IF NOT EXISTS texture TEXT DEFAULT 'marble';
ALTER TABLE public.colours ADD COLUMN IF NOT EXISTS image_url TEXT DEFAULT '';
ALTER TABLE public.colours ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT true;
ALTER TABLE public.colours ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();


-- =========================================================================
-- SECTION 3: CATEGORIES TABLE
-- =========================================================================
-- Used by the admin dashboard to manage stone type categories
-- (Marble, Granite, Quartz, Porcelain, Sintered Stone, etc.)
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT DEFAULT '🪨',
    enabled BOOLEAN DEFAULT true,
    display_order INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS icon TEXT DEFAULT '🪨';
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT true;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS display_order INT DEFAULT 1;

-- Seed default categories if the table is empty
INSERT INTO public.categories (name, icon, enabled, display_order)
SELECT name, icon, enabled, display_order FROM (VALUES
    ('Marble',         '🤍', true, 1),
    ('Granite',        '🖤', true, 2),
    ('Quartz',         '💎', true, 3),
    ('Quartzite',      '🪨', true, 4),
    ('Porcelain',      '⬜', true, 5),
    ('Sintered Stone', '🔷', true, 6),
    ('Limestone',      '🟤', false, 7),
    ('Onyx',           '💜', false, 8),
    ('Travertine',     '🪵', false, 9)
) AS t(name, icon, enabled, display_order)
WHERE NOT EXISTS (SELECT 1 FROM public.categories LIMIT 1);


-- =========================================================================
-- SECTION 4: ROW LEVEL SECURITY POLICIES
-- =========================================================================
-- These policies allow ALL roles (anon, authenticated, public) to
-- SELECT, INSERT, UPDATE, DELETE on all three tables. This ensures
-- the admin dashboard and the public-facing app can both read/write.
-- =========================================================================

-- Brands RLS
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public full access to brands" ON public.brands;
CREATE POLICY "Allow public full access to brands" ON public.brands
    FOR ALL TO public USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access to brands" ON public.brands;
CREATE POLICY "Allow anon full access to brands" ON public.brands
    FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access to brands" ON public.brands;
CREATE POLICY "Allow authenticated full access to brands" ON public.brands
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Also drop old policies if they exist from a previous migration
DROP POLICY IF EXISTS "Allow all access to brands" ON public.brands;
DROP POLICY IF EXISTS "Allow authenticated access to brands" ON public.brands;
DROP POLICY IF EXISTS "Allow anon access to brands" ON public.brands;


-- Colours RLS
ALTER TABLE public.colours ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public full access to colours" ON public.colours;
CREATE POLICY "Allow public full access to colours" ON public.colours
    FOR ALL TO public USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access to colours" ON public.colours;
CREATE POLICY "Allow anon full access to colours" ON public.colours
    FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access to colours" ON public.colours;
CREATE POLICY "Allow authenticated full access to colours" ON public.colours
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Also drop old policies if they exist from a previous migration
DROP POLICY IF EXISTS "Allow all access to colours" ON public.colours;
DROP POLICY IF EXISTS "Allow authenticated access to colours" ON public.colours;
DROP POLICY IF EXISTS "Allow anon access to colours" ON public.colours;


-- Categories RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public full access to categories" ON public.categories;
CREATE POLICY "Allow public full access to categories" ON public.categories
    FOR ALL TO public USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access to categories" ON public.categories;
CREATE POLICY "Allow anon full access to categories" ON public.categories
    FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated full access to categories" ON public.categories;
CREATE POLICY "Allow authenticated full access to categories" ON public.categories
    FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =========================================================================
-- SECTION 5: FORCE POSTGREST SCHEMA CACHE RELOAD
-- =========================================================================
-- This is CRITICAL — without this, PostgREST will keep using its cached
-- schema and new columns will not be visible until the next auto-reload.
-- =========================================================================

NOTIFY pgrst, 'reload schema';


-- =========================================================================
-- DONE! You should now see:
--   brands table with: id, name, category, description, enabled, created_at
--   colours table with: id, brand_id, brand_name, name, sku, finish,
--                          texture, image_url, enabled, created_at
--   categories table with: id, name, icon, enabled, display_order, created_at
--   Full RLS policies for anon + authenticated + public on all 3 tables
-- =========================================================================
